-- =====================================================
-- Asset Monitoring System
-- Core Tables
-- =====================================================

---------------------------------------------------------
-- Profiles
---------------------------------------------------------
CREATE TABLE profiles (

    id UUID PRIMARY KEY,

    employee_no INT4 GENERATED BY DEFAULT AS IDENTITY,

    employee_code TEXT NOT NULL UNIQUE,

    role_id UUID NOT NULL,
    department_id UUID NOT NULL,
    location_id UUID NOT NULL,

    display_name TEXT,
    first_name TEXT NOT NULL,
    middle_name TEXT,
    last_name TEXT NOT NULL,
    suffix TEXT,

    email TEXT NOT NULL UNIQUE,
    contact_number TEXT,

    position TEXT,

    profile_image_file_id UUID,

    last_login_at TIMESTAMPTZ,

    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    deleted_at TIMESTAMPTZ,

    created_by UUID,
    updated_by UUID,

    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT fk_profile_auth
        FOREIGN KEY (id)
        REFERENCES auth.users(id)
        ON DELETE CASCADE,

    CONSTRAINT fk_profile_role
        FOREIGN KEY (role_id)
        REFERENCES roles(id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_profile_department
        FOREIGN KEY (department_id)
        REFERENCES departments(id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_profile_location
        FOREIGN KEY (location_id)
        REFERENCES locations(id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_profile_image
        FOREIGN KEY (profile_image_file_id)
        REFERENCES media(id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    CONSTRAINT fk_profile_created_by
        FOREIGN KEY (created_by)
        REFERENCES profiles(id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    CONSTRAINT fk_profile_updated_by
        FOREIGN KEY (updated_by)
        REFERENCES profiles(id)
        ON UPDATE CASCADE
        ON DELETE SET NULL
);

---------------------------------------------------------
-- Assets
---------------------------------------------------------
CREATE TABLE assets (

    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),

    asset_no INT4 GENERATED BY DEFAULT AS IDENTITY,

    asset_code TEXT NOT NULL UNIQUE,

    asset_tag TEXT UNIQUE,

    asset_name TEXT NOT NULL,
    description TEXT,

    category_id UUID NOT NULL,
    model_id UUID NOT NULL,
    supplier_id UUID,
    location_id UUID NOT NULL,

    status_id UUID NOT NULL,
    condition_id UUID NOT NULL,

    serial_number TEXT UNIQUE,

    purchase_date DATE,

    purchase_cost NUMERIC(12,2)
        CHECK (purchase_cost IS NULL OR purchase_cost >= 0),

    current_value NUMERIC(12,2)
        CHECK (current_value IS NULL OR current_value >= 0),

    warranty_end_date DATE,

    asset_image_file_id UUID,

    notes TEXT,
    qr_code TEXT,
    barcode TEXT,

    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    deleted_at TIMESTAMPTZ,

    created_by UUID,
    updated_by UUID,

    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now(),

    CONSTRAINT fk_asset_category
        FOREIGN KEY (category_id)
        REFERENCES categories(id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_asset_model
        FOREIGN KEY (model_id)
        REFERENCES models(id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_asset_supplier
        FOREIGN KEY (supplier_id)
        REFERENCES suppliers(id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    CONSTRAINT fk_asset_location
        FOREIGN KEY (location_id)
        REFERENCES locations(id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_asset_status
        FOREIGN KEY (status_id)
        REFERENCES asset_statuses(id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_asset_condition
        FOREIGN KEY (condition_id)
        REFERENCES asset_conditions(id)
        ON UPDATE CASCADE
        ON DELETE RESTRICT,

    CONSTRAINT fk_asset_image
        FOREIGN KEY (asset_image_file_id)
        REFERENCES media(id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    CONSTRAINT fk_asset_created_by
        FOREIGN KEY (created_by)
        REFERENCES profiles(id)
        ON UPDATE CASCADE
        ON DELETE SET NULL,

    CONSTRAINT fk_asset_updated_by
        FOREIGN KEY (updated_by)
        REFERENCES profiles(id)
        ON UPDATE CASCADE
        ON DELETE SET NULL
);